services:
  db:
    image: mysql:8.0
    container_name: evaluation_system_v1
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: evalPassword
      MYSQL_USER: evalUser
      MYSQL_DATABASE: evaluation_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - eval_net

volumes:
  db_data:
    driver: local

networks:
  eval_net:
    driver: bridge
